### ISSUE TITLE
Documentation about Rayonix files

### ISSUE THREAD

**Issue by apeck12** [lcls-users/mrxv#5]
Rayonix files from mfxlv4920 were generated as follows. For the the mask:
```
mi = MaskInterface(exp='mfxlv4920', run=234, det_type='Rayonix')
mask = mi.generate_from_psana_run(thresholds=(-50,5000), n_images=10)
```
For the geom, the `run_analysis` and `opt_distance` tasks were called using the following parameters:
```
run_analysis:
  max_events: -1
  mask: '/cds/data/psdm/mfx/mfxlv4920/scratch/apeck/rayonix_mask.npy'

opt_distance:
  center: 960 960
  input_geom: '/cds/data/psdm/mfx/mfxlv4920/scratch/apeck/176-end.data'
```
@fredericpoitevin , sorry I should have made a PR instead of an Issue, but if you see anything amiss with the above, happy to make changes.
